name: ready_basket1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2  # Use the latest version
  cloud_firestore: ^4.13.2
  image_picker: ^1.0.7  # Latest version at the time
  flutter_icons: ^1.1.0
  provider: ^6.0.0
  razorpay_flutter: ^1.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/shopping_girl.png
    - assets/girl_on_cart.png

    - assets/settings.png
    - assets/home.png
    - assets/Categories.png
    - assets/cart.png
    - assets/search.png
    - assets/beverages.png
    - assets/vegetables.png
    - assets/milk_egg.png
    - assets/orders.png
    - assets/support.png
    - assets/profile.png
    - assets/P_P.png
    - assets/notifications.png
    - assets/c_vegetables.png
    - assets/dairy.png
    - assets/rice_oil_dal.png
    - assets/dry_fruits.png
    - assets/packed_food.png
    - assets/soap_shampoo.png
    - assets/tea_coffee.png
    - assets/ice_cream.png
    - assets/munchies.png
    - assets/sweets_chocolates.png
    - assets/cool_drinks.png
    - assets/cakes.png

  fonts:
    - family: Irish Grover
      fonts:
        - asset: fonts/IrishGrover-Regular.ttf
dependency_overrides:
  flutter_icons: any
